FROM arm64v8/alpine:3.8 as build
RUN apk update && apk add build-base go git libzmq zeromq-dev alpine-sdk libsodium-dev

RUN addgroup -S databox && adduser -S -g databox databox
RUN go get -u github.com/gorilla/mux
RUN go get -u github.com/me-box/lib-go-databox
RUN go get -u github.com/google/uuid
COPY /src /src
COPY /static /static
RUN GGO_ENABLED=0 GOOS=linux go build -a -ldflags '-s -w' -o driver /src/*.go

FROM arm64v8/alpine:3.8
RUN addgroup -S databox && adduser -S -g databox databox
RUN apk update && apk add libzmq && apk add python && apk add py-pip && apk add ca-certificates
RUN pip install --upgrade pip
USER databox
RUN pip install --user instagram-scraper && pip install --user instagram-scraper --upgrade
WORKDIR /
COPY --from=build /driver /driver
COPY --from=build /static /static
LABEL databox.type="driver"
EXPOSE 8080
CMD ["/driver"]